version: '3.4'

services:

  wordpress:
    container_name: wordpress
    ports:
      - '8080:80'
    restart: always
    volumes:
      - '/wp_data:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: apostolos
      WORDPRESS_DB_NAME: wordpress
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '500M'
        reservations:
          cpus: '0.05'
          memory: '50M'
    networks:
      - wordpressNetwork

networks:
  wordpressNetwork:
    driver: bridge
