version: '3.4'

services: 
  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 200M
        reservations:
          cpus: '0.05'
          memory: 50M
    networks:
      - wordpressNetwork

networks:
  wordpressNetwork:
    driver: bridge
    external: true
