 mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: john 
      MYSQL_DATABASE: java-app
      MYSQL_USER: john
      MYSQL_PASSWORD: john 
    networks:
      - java-appNetwork
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  wordpressNetwork:
    driver: bridge
    external: true
