version: '3.4'

services:

  portainer:
    image: portainer/portainer-ce:latest
    networks:
      - wordpressNetwork

networks:
  wordpressNetwork:
    driver: bridge
    external: true
