version: '3.4'

services: 
  portainer:
    container_name: portainer
    ports:
      - '9443:9443'
    restart: always
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 50M
    networks:
      - wordpressNetwork

volumes:
  data:
    driver: local

networks:
  wordpressNetwork:
    driver: bridge
    external: true
